# Generated by Django 3.0.4 on 2020-08-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20200802_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='allow_comments',
            field=models.BooleanField(default=True, verbose_name='allow comments'),
        ),
    ]
